spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    database: POSTGRESQL
    hibernate:
      ddl-auto: update
  servlet:
    multipart:
      enabled: true
      max-file-size: 15MB
      max-request-size: 20MB

server:
  port: ${SERVER_PORT}

aws:
  s3:
    access-key-id: <access key>
    secret-access-key: <secret_key>
    bucket-name: <bucket>
    region: <aws-region>
    poster-folder: <folder for posters>
    preview-folder: <folder for previews>
