spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    database: POSTGRESQL
    hibernate:
      ddl-auto: update
  servlet:
    multipart:
      enabled: true
      max-file-size: 20MB
      max-request-size: 50MB
  mvc:
    format:
      date: yyyy-MM-dd
  mail:
    host: ${MAIL_SERVER}
    port: ${MAIL_SERVER_PORT}
    username: ${MAIL_SERVER_USERNAME}
    password: ${MAIL_SERVER_PASSWORD}
    properties:
      mail:
        smtp:
          ssl:
            trust: "*"
          auth: true
          starttls:
            enable: true

mail:
  from: ${MAIL_FROM:noreply@example.com}

logging:
  level:
    root: INFO
    com.example.cinema: DEBUG

server:
  port: ${SERVER_PORT:8080}

images:
  allowed-extensions-regex: (jp.?g|png|bmp|webp)
  aws:
    s3:
      access-key-id: ${S3_ACCESS_KEY}
      secret-access-key: ${S3_SECRET_KEY}
      bucket-name: ${S3_BUCKET}
      region: ${S3_REGION}
      poster-folder: ${S3_POSTER_FOLDER}
      preview-folder: ${S3_PREVIEW_FOLDER}